export const COLORS = {
  bg: '#0B0E17',
  card: '#121624',
  accent: '#00E5FF',
  purple: '#8B5CF6',
  gold: '#F59E0B',
};

export const BATTLE_STATUSES = {
  OPEN: 'OPEN',
  JOINED: 'JOINED',
  IN_PROGRESS: 'IN_PROGRESS',
  RESULT_SUBMITTED: 'RESULT_SUBMITTED',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  COMPLETED: 'COMPLETED',
  DISPUTED: 'DISPUTED',
  CANCELLED: 'CANCELLED',
} as const;

export const TRANSACTION_TYPES = {
  DEPOSIT: 'DEPOSIT',
  WITHDRAW: 'WITHDRAW',
  BATTLE_ENTRY: 'BATTLE_ENTRY',
  BATTLE_WIN: 'BATTLE_WIN',
  BATTLE_REFUND: 'BATTLE_REFUND',
  REFERRAL_BONUS: 'REFERRAL_BONUS',
  ADMIN_CREDIT: 'ADMIN_CREDIT',
  ADMIN_DEBIT: 'ADMIN_DEBIT',
} as const;
